name: Run tests

on:
  pull_request:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
    branches:
      - dev
      - main
      - multi-generator
concurrency:
  # cancel intermediate builds
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    name: Julia Tests ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ matrix.julia-arch }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.10', '1.11', '1.12']
        julia-arch: [x64, aarch64]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        exclude:
          - os: macOS-latest
            julia-arch: x86
          - os: macOS-latest
            julia-arch: x64
          - os: windows-latest
            julia-arch: aarch64
          - os: ubuntu-latest
            julia-arch: aarch64

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Set up Julia
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
      - name: Cache artifacts
        uses: julia-actions/cache@v2
      #- name: Build package
      #  uses: julia-actions/julia-buildpkg@v1
      - name: Instantiate Julia Package
        run: julia --project=. -e 'using Pkg; Pkg.add(url="https://github.com/samysweb/VNNLib.jl", rev="9327e5c"); Pkg.pin("VNNLib"); Pkg.resolve()'
      - name: Run tests
        uses: julia-actions/julia-runtest@v1
        env:
          VERYDIFF_NO_GUROBI: 1